kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-mysql-pvc-with-cs-schedule
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-with-cloudsnap-schedules
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
