apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
  namespace: prisma
  labels:
    stage: production
    name: prisma
    app: prisma
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector: 
    matchLabels: 
      app: prisma
  template:
    metadata:
      labels:
        stage: production
        name: prisma
        app: prisma
    spec:
      containers:
      - name: prisma
        image: 'prismagraphql/prisma:1.8'
        ports:
          - name: prisma-4466
            containerPort: 4466
        env:
        - name: PRISMA_CONFIG
          valueFrom:
            configMapKeyRef:
              name: prisma-configmap
              key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prisma
spec:
  ports:
  - port: 4466
    targetPort: 4466
    protocol: TCP
  selector:
    stage: production
    name: prisma
    app: prisma
