## PVC from local snapshot
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-postgres-snap-clone
  namespace: postgres
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: px-postgres-snapshot ## use snapshot name
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc ## reference stork SC to handle cloning of volume
  resources:
    requests:
      storage: 2Gi
