apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmanager
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: admin-credentials # Should match metadata.name
                                           # in the Kubernetes secret
                                           # for the admin user
  externalConnectivity:
    type: NodePort
  applicationDatabase:
    members: 3
    version: 4.2.2
    persistent: true
    podSpec:
      persistence:
        multiple:
          data:
            storage: 16G
            storageClass: px-ha
          journal:
            storage: 1G
            storageClass: px-ha
          logs:
            storage: 1G
            storageClass: px-repl1
      podTemplate:
        spec:
          schedulerName: stork
  backup:
    enabled: true
    headDB:
      storage: 30G
      storageClass: px-repl1
      labelSelector:
        matchLabels:
          app: my-replica-set
    opLogStores:
    - name: oplog1
      mongodbResourceRef:
        name: opsmanager-db
    blockStores:
    - name: blockstore-1
      mongodbResourceRef:
        name: my-replica-set
