kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-ha
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db"
  priority_io: "high"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-repl1
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
