kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-high-rf2
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "ext4"
  block_size: "4k"
  shared: "false"
  repl: "2"
  snap_interval:   "0"
  priority_io:  "high"
