kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: {{ .Values.persistence.storageClass | quote }}
    namespace: portworx
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "sequential"
   priority_io: "high"
   journal: "true"
allowVolumeExpansion: true
