---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: mongo-rs

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-user-full-access
  namespace: mongo-rs
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-view
  namespace: mongo-rs
subjects:
- kind: ServiceAccount
  name: mongo
  namespace: mongo-rs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongo-user-full-access
