kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-data
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
   io_priority: "high"
   placement_strategy: "statefulset-data"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-config
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
   io_priority: "low"
   placement_strategy: "statefulset-config"
