apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: daily-schedule
policy:
  interval:
    intervalMinutes: 120
    retain: 6 
  daily:
    time: "10:14PM"
    retain: 7 
