apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: postgres-backup-schedule
  namespace: postgres
spec:
  schedulePolicyName: daily-schedule
  template:
    spec:
      backupLocation: postgres-backup-location
      namespaces:
      - postgres
      reclaimPolicy: Delete
