apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  backupLocation: postgres-backup-location
  namespaces:
  - postgres
  reclaimPolicy: Delete
  selectors:
  preExecRule:
  postExecRule:
