apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mongo-init
  name: mongo-init
  namespace: mongo-rs
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: mongo-init
    spec:
      containers:
      - command:
        - mongo
        - --host
        - $(MONGO_ROOT_PRIMARY_NODE)
        - $(MONGO_ROOT_DATABASE)
        - /opt/config/repl_set_initiate.js
        env:
        - name: MONGO_ROOT_PRIMARY_NODE
          value: mongo-rs-0.mongo-rs.mongo-rs.svc.cluster.local:27017
        - name: MONGO_ROOT_DATABASE
          value: admin
        image: mongo:4.1.5
        imagePullPolicy: IfNotPresent
        name: mongo-init
        ports:
        - containerPort: 27017
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mongo-rs
        name: config-volume

