kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gp-master-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  group: "gp-master"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gp-segment-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  group: "gp-segment"
