apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 7.7.0
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    service:
      spec:
        type: NodePort
